F0TRACK ; Multi-F0 Tracker Database Backend in ANSI MUMPS for YottaDB
        ; This module implements the state management and tracking data
        ; structures using MUMPS globals, ideal for persistent hierarchical data.
        ;
START   WRITE !,"Initializing A Cappella Tracker Database in YottaDB...",!
        KILL ^F0TRACK
        SET ^F0TRACK("CONFIG","MAX_VOICES")=8
        SET ^F0TRACK("CONFIG","MIN_FREQ")=65
        SET ^F0TRACK("CONFIG","MAX_FREQ")=1400
        SET ^F0TRACK("STATE")="READY"
        WRITE "Tracker Configuration Stored in ^F0TRACK Global.",!
        QUIT

ADDPITCH(TRACKID,FRAME,FREQ,CONF) ; Add a pitch observation to a track
        ; ^F0TRACK("TRACKS", track_id, frame_id) = frequency ^ confidence
        SET ^F0TRACK("TRACKS",TRACKID,FRAME)=FREQ_"^"_CONF
        WRITE "Added pitch ",FREQ," Hz to Track ",TRACKID," at Frame ",FRAME,!
        QUIT

TERMINAT(TRACKID) ; Mark a track as terminated
        SET ^F0TRACK("TRACKS",TRACKID,"STATE")="TERMINATED"
        WRITE "Track ",TRACKID," terminated.",!
        QUIT

PROCESS ; Process raw DSP frames generated by the C++ Engine (from ^F0TRACK("FRAME"))
        NEW FRM,PIDX,DATA,FREQ,CONF
        WRITE !,"Processing DSP frames from ^F0TRACK(""FRAME"")...",!
        SET FRM=""
        FOR  SET FRM=$ORDER(^F0TRACK("FRAME",FRM)) QUIT:FRM=""  DO
        . WRITE "  Analyzing Frame ",FRM,!
        . SET PIDX=""
        . FOR  SET PIDX=$ORDER(^F0TRACK("FRAME",FRM,PIDX)) QUIT:PIDX=""  DO
        . . SET DATA=^F0TRACK("FRAME",FRM,PIDX)
        . . SET FREQ=$PIECE(DATA,"^",1)
        . . SET CONF=$PIECE(DATA,"^",2)
        . . ; In a fully complete tracker, the Hungarian assignment algorithm would run here.
        . . ; For this architectural demo, we blindly map pitch indices to track IDs.
        . . DO ADDPITCH(PIDX,FRM,FREQ,CONF)
        WRITE "Finished processing frames.",!
        QUIT

DEMO    ; Run a full simulated demonstration
        DO START
        WRITE !,"(Normally, you would run the C++ executable now to populate frames)",!
        WRITE "(Simulating C++ DSP Engine push...)",!
        SET ^F0TRACK("FRAME",0,1)="440.00^0.95", ^F0TRACK("FRAME",0,2)="554.37^0.88"
        SET ^F0TRACK("FRAME",1,1)="442.50^0.95", ^F0TRACK("FRAME",1,2)="555.87^0.88"
        SET ^F0TRACK("FRAME",2,1)="445.00^0.95", ^F0TRACK("FRAME",2,2)="557.37^0.88"
        DO PROCESS
        DO REPORT
        QUIT

REPORT  ; Print summary of all tracked voices
        NEW TRK,FRM,DATA,STATE
        WRITE !,"--- YOTTADB MULTI-F0 TRACKING REPORT ---",!
        SET TRK=""
        FOR  SET TRK=$ORDER(^F0TRACK("TRACKS",TRK)) QUIT:TRK=""  DO
        . WRITE "Voice Track ",TRK
        . SET STATE=$GET(^F0TRACK("TRACKS",TRK,"STATE"),"ACTIVE")
        . WRITE " (",STATE,"):",!
        . SET FRM=""
        . FOR  SET FRM=$ORDER(^F0TRACK("TRACKS",TRK,FRM)) QUIT:FRM=""  DO
        . . IF FRM="STATE" QUIT  ; Skip state metadata node
        . . SET DATA=^F0TRACK("TRACKS",TRK,FRM)
        . . WRITE "  Frame ",FRM," -> Freq: ",$PIECE(DATA,"^",1)," Hz, Conf: ",$PIECE(DATA,"^",2),!
        WRITE "--- END OF REPORT ---",!
        QUIT
